### PR TITLE
Fixes #23, error with headless mode where user agent tuple is incorrectly processed

### LINKED ISSUE #23: Headless mode fails due to incorrect processing of CDP user agent message
I am trying to use zendriver in a simple AWS-based debian box (via [Modal](https://modal.com)) with headless Chrome. I installed the `chromium` package via `apt-get` and then tried running the following code in the Python interpreter:

```
import zendriver as uc

async def open_page():
    browser = await uc.start(sandbox=False, headless=True)
    page = await browser.get('https://www.google.com')
    print(await page.get_content())
    await browser.stop()

uc.loop().run_until_complete(open_page())
``` 

This yields an `AttributeError` saying `'tuple' object has no attribute 'value'` in the `_prepare_headless` call:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "<stdin>", line 3, in open_page
  File "/usr/local/lib/python3.11/site-packages/zendriver/core/browser.py", line 271, in get
    frame_id, loader_id, *_ = await connection.send(cdp.page.navigate(url))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zendriver/core/connection.py", line 422, in send
    await self._prepare_headless()
  File "/usr/local/lib/python3.11/site-packages/zendriver/core/connection.py", line 509, in _prepare_headless
    if response and response.value:
                    ^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'value'
```

This `response` object is coming from a CDP call where zendriver tries to get the userAgent:

```
response = await self._send_oneshot(
    cdp.runtime.evaluate(
        expression="navigator.userAgent",
        user_gesture=True,
        await_promise=True,
        return_by_value=True,
        allow_unsafe_eval_blocked_by_csp=True,
    )
)
```

It appears that this response object is actually a tuple that looks like this: `(RemoteObject(type_='string', subtype=None, class_name=None, value='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/120.0.0.0 Safari/537.36', unserializable_value=None, description=None, deep_serialized_value=None, object_id=None, preview=None, custom_preview=None), None)`

The value `_prepare_headless` is trying to extract is hence not at `response.value`, but rather `response[0].value`. I am making a PR to fix this.

# Error profile

- `zendriver` version: `zendriver==0.2.0`
- OS/platform: `Debian GNU/Linux 11 (bullseye)`
- Linux kernel version: `4.4.0`
- Python version: `3.11.0`
- Chrome version: `120.0.6099.224`
- Can you reliably reproduce the issue?: Yes, see above.

### PR DESCRIPTION
**Pull request by slimshreydy**
See #23 for more.

Currently, attempts to use `zendriver` in Headless mode fail because the CDP call to get the `userAgent` actually outputs a tuple, but `zendriver` doesn't index into this tuple correctly. This PR rectifies the issue.

I've been able to replicate this bug both in my local macOS/Darwin env, and a cloud debian-based env.

### CODE REVIEW

**Comment by slimshreydy** [comment]
Can't get the issue linking to work, so linking via comment: #23

**Comment by stephanlensky** [comment]
I just added some capability for automated testing w/ pytest today, and I just pushed a change which attempts to run all tests with the headless browser.

I'm currently seeing the same issue as you when trying to run some basic tests w/ headless browser.

I'm going to merge my latest into your branch once more to confirm that the tests pass after your change.

**Review by stephanlensky — APPROVED** [review]
Again thanks for the PR! I was able to confirm w/ tests that headless is currently broken, and after adding your change the tests now pass.

I'm going to merge this and cut a new release.

**Comment by slimshreydy** [comment]
Appreciate it! Thank you stephan!

**Pull request merged**
